### ISSUE TITLE
fix(timestamp)!: change column type timestamp to timestamptz

### ISSUE THREAD

**Issue by sthelemann** [maevsi/sqitch#67]
I noticed that some table columns have data type `timestamp` while others have data type `timestamptz`. 
We should generally use data type `timestamptz` (or `timestamp with time zone`).

**Comment by dargmuesli** [comment]
You're right! Good catch :pray: 
Would you like to try implementing this change as next step? Small code changes allow for focus on understanding the git flow, then we can transition to tasks that are on the more extensive feature side as next step :sparkles:
